import { ItemDomain, ItemType, PropUnitDataType } from '@core/models/item.model'

const sensor = '#62b4c1'
const heatingSensor = '#3d909c'
const boilerSensor = '#296068'
const pv = '#143034'
const actuator = '#8DA572'

export const itemDomains: ItemDomain[] = [
  {
    name: 'Energy',
    icon: 'bolt',
    color: '#e1d81e',
  },
  {
    name: 'Mobility',
    icon: 'bus-simple',
    color: '#3a88c5',
  },
  {
    name: 'Health',
    icon: 'briefcase-medical',
    color: '#cf3a30',
  },
  {
    name: 'Farming',
    icon: 'tractor',
    color: '#63a25d',
  },
  {
    name: 'Tourism',
    icon: 'suitcase',
    color: '#b4744b',
  },
  {
    name: 'Weather',
    icon: 'sun',
    color: '#edcc12',
  },
  {
    name: 'Indoor quality',
    icon: 'house-user',
    color: '#5e8fa1',
  },
  {
    name: 'Industry',
    icon: 'industry',
    color: '#e18b1e',
  },
]

export const itemTypes: ItemType[] = [
  {
    id: '1',
    title: 'Device',
    icon: 'rss',
    color: '#00B6EB',
  },
  {
    id: '2',
    title: 'Service',
    icon: 'cloud',
    color: '#E5B38E',
  },
  {
    id: '3',
    title: 'Dataset',
    icon: 'file-lines',
    color: '#979797',
  },
  {
    id: '4',
    title: 'Sensor',
    icon: 'gauge-simple-high',
    color: sensor,
  },
  {
    id: '5',
    title: 'QRGeneratorSensor',
    icon: 'qrcode',
    color: sensor,
  },
  {
    id: '6',
    title: 'PersonCounterSensor',
    icon: 'stopwatch-20',
    color: sensor,
  },
  {
    id: '7',
    title: 'FloodSensor',
    icon: 'droplet',
    color: sensor,
  },
  {
    id: '8',
    title: 'EnergyMonitor',
    icon: 'bolt',
    color: sensor,
  },
  {
    id: '9',
    title: 'MotionSensor',
    icon: 'person-walking',
    color: sensor,
  },
  {
    id: '10',
    title: 'HumiditySensor',
    icon: 'droplet',
    color: sensor,
  },
  {
    id: '11',
    title: 'Thermometer',
    icon: 'temperature-three-quarters',
    color: sensor,
  },
  {
    id: '12',
    title: 'GPSEmergencyButton',
    icon: 'truck-medical',
    color: sensor,
  },
  {
    id: '13',
    title: 'WaterAMRSensor',
    icon: 'droplet',
    color: sensor,
  },
  {
    id: '14',
    title: 'Accelerometer',
    icon: 'gauge-simple-high',
    color: sensor,
  },
  {
    id: '15',
    title: 'PressureSensor',
    icon: 'gauge-simple-high',
    color: sensor,
  },
  {
    id: '16',
    title: 'SoundSensor',
    icon: 'volume-low',
    color: sensor,
  },
  {
    id: '17',
    title: 'UltrasoundSensor',
    icon: 'volume-low',
    color: sensor,
  },
  {
    id: '18',
    title: 'MonitoringSensor',
    icon: 'eye',
    color: sensor,
  },
  {
    id: '19',
    title: 'WeatherSensor',
    icon: 'sun',
    color: sensor,
  },
  {
    id: '20',
    title: 'WasteBinSensor',
    icon: 'trash-can',
    color: sensor,
  },
  {
    id: '21',
    title: 'SoilMoistureSEnsor',
    icon: 'droplet',
    color: sensor,
  },
  {
    id: '22',
    title: 'LightBulb',
    icon: 'lightbulb',
    color: sensor,
  },
  {
    id: '23',
    title: 'AirQualitySensor',
    icon: 'wind',
    color: sensor,
  },
  {
    id: '24',
    title: 'Presence_Sensor',
    icon: 'person-walking',
    color: sensor,
  },
  {
    id: '25',
    title: 'SmartPlug',
    icon: 'plug',
    color: sensor,
  },
  {
    id: '26',
    title: 'BatterySensor',
    icon: 'battery-three-quarters',
    color: sensor,
  },
  {
    id: '27',
    title: 'HeatingSensor',
    icon: 'temperature-three-quarters',
    color: heatingSensor,
  },
  {
    id: '28',
    title: 'CoolingSensor',
    icon: 'snowflake',
    color: heatingSensor,
  },
  {
    id: '29',
    title: 'AirConditionningBasic',
    icon: 'snowflake',
    color: heatingSensor,
  },
  {
    id: '30',
    title: 'HeatPumpAirtoWater',
    icon: 'droplet',
    color: heatingSensor,
  },
  {
    id: '31',
    title: 'HeatPumpAirtoAir',
    icon: 'wind',
    color: heatingSensor,
  },
  {
    id: '32',
    title: 'BoilerSensor',
    icon: 'fire-flame-simple',
    color: boilerSensor,
  },
  {
    id: '33',
    title: 'BoilerOil',
    icon: 'oil-can',
    color: boilerSensor,
  },
  {
    id: '34',
    title: 'BoilerNgas',
    icon: 'fire-flame-simple',
    color: boilerSensor,
  },
  {
    id: '35',
    title: 'BoilerBiomass',
    icon: 'tree',
    color: boilerSensor,
  },
  {
    id: '36',
    title: 'PV',
    icon: 'solar-panel',
    color: pv,
  },
  {
    id: '37',
    title: 'PVGround',
    icon: 'solar-panel',
    color: pv,
  },
  {
    id: '38',
    title: 'PVRoofStanled',
    icon: 'solar-panel',
    color: pv,
  },
  {
    id: '39',
    title: 'PVRoofFlat',
    icon: 'solar-panel',
    color: pv,
  },
  {
    id: '40',
    title: 'PVFaçade',
    icon: 'solar-panel',
    color: pv,
  },
  {
    id: '41',
    title: 'PVBIntegrated',
    icon: 'solar-panel',
    color: pv,
  },
  {
    id: '42',
    title: 'Actuator',
    icon: 'power-off',
    color: actuator,
  },
  {
    id: '43',
    title: 'WaterValveActuator',
    icon: 'faucet-drip',
    color: actuator,
  },
  {
    id: '44',
    title: 'Switch',
    icon: 'toggle-on',
    color: actuator,
  },
  {
    id: '45',
    title: 'Relay',
    icon: 'power-off',
    color: actuator,
  },
  {
    id: '46',
    title: 'SmartValve',
    icon: 'faucet-drip',
    color: actuator,
  },
]

export const unitDataTypes: PropUnitDataType[] = [
  {
    name: 'number',
    symbol: '123',
  },
  {
    name: 'integer',
    symbol: 'int',
  },
  {
    name: 'boolean',
    symbol: 'bool',
  },
  {
    name: 'string',
    symbol: 'abc',
  },
  {
    name: 'object',
    symbol: '{}',
  },
  {
    name: 'array',
    symbol: '[]',
  },
]

export const apdaptersOntologyTypes = [
  'http://www.semanticweb.org/user/ontologies/2022/5/adapters#WindDirection',
  'https://auroral.iot.linkeddata.es/def/adapters#AccumulatedWater',
  'https://auroral.iot.linkeddata.es/def/adapters#ActiveEnergy',
  'https://auroral.iot.linkeddata.es/def/adapters#AirPressureAtSea',
  'https://auroral.iot.linkeddata.es/def/adapters#Alarm',
  'https://auroral.iot.linkeddata.es/def/adapters#AmbientTemperature',
  'https://auroral.iot.linkeddata.es/def/adapters#AmountPrecipitation',
  'https://auroral.iot.linkeddata.es/def/adapters#AngularUnit',
  'https://auroral.iot.linkeddata.es/def/adapters#AtmosphericPressure',
  'https://auroral.iot.linkeddata.es/def/adapters#Available',
  'https://auroral.iot.linkeddata.es/def/adapters#AverageMovementShare',
  'https://auroral.iot.linkeddata.es/def/adapters#AverageMovementTime',
  'https://auroral.iot.linkeddata.es/def/adapters#BasalMetabolicRate',
  'https://auroral.iot.linkeddata.es/def/adapters#Battery',
  'https://auroral.iot.linkeddata.es/def/adapters#BatteryLevel',
  'https://auroral.iot.linkeddata.es/def/adapters#BeaconMac',
  'https://auroral.iot.linkeddata.es/def/adapters#BodyFatPercentage',
  'https://auroral.iot.linkeddata.es/def/adapters#BodyMassIndex',
  'https://auroral.iot.linkeddata.es/def/adapters#BoneMineralContent',
  'https://auroral.iot.linkeddata.es/def/adapters#Button',
  'https://auroral.iot.linkeddata.es/def/adapters#CO2Concentration',
  'https://auroral.iot.linkeddata.es/def/adapters#COConcentration',
  'https://auroral.iot.linkeddata.es/def/adapters#CaloriesBurned',
  'https://auroral.iot.linkeddata.es/def/adapters#Cloudiness',
  'https://auroral.iot.linkeddata.es/def/adapters#DeviceStatus',
  'https://auroral.iot.linkeddata.es/def/adapters#DewpointTemperature',
  'https://auroral.iot.linkeddata.es/def/adapters#DiastolicBloodPressure',
  'https://auroral.iot.linkeddata.es/def/adapters#DiffuseRadiation',
  'https://auroral.iot.linkeddata.es/def/adapters#DiffuseRadiationInstant',
  'https://auroral.iot.linkeddata.es/def/adapters#DirectNormalIrradiance',
  'https://auroral.iot.linkeddata.es/def/adapters#DirectNormalIrradianceInstant',
  'https://auroral.iot.linkeddata.es/def/adapters#DirectRadiation',
  'https://auroral.iot.linkeddata.es/def/adapters#DirectRadiationInstant',
  'https://auroral.iot.linkeddata.es/def/adapters#Distance',
  'https://auroral.iot.linkeddata.es/def/adapters#DistanceWalked',
  'https://auroral.iot.linkeddata.es/def/adapters#DivPosition',
  'https://auroral.iot.linkeddata.es/def/adapters#ElectricCurrent',
  'https://auroral.iot.linkeddata.es/def/adapters#ElectricVoltage',
  'https://auroral.iot.linkeddata.es/def/adapters#EnergyConsumption',
  'https://auroral.iot.linkeddata.es/def/adapters#EnergyProduction',
  'https://auroral.iot.linkeddata.es/def/adapters#EnergyUseIntensity',
  'https://auroral.iot.linkeddata.es/def/adapters#Flood',
  'https://auroral.iot.linkeddata.es/def/adapters#Fog',
  'https://auroral.iot.linkeddata.es/def/adapters#GPSAltitude',
  'https://auroral.iot.linkeddata.es/def/adapters#GPSLatitude',
  'https://auroral.iot.linkeddata.es/def/adapters#GPSLongitude',
  'https://auroral.iot.linkeddata.es/def/adapters#GridCapacity',
  'https://auroral.iot.linkeddata.es/def/adapters#GridDemand',
  'https://auroral.iot.linkeddata.es/def/adapters#GridFrequency',
  'https://auroral.iot.linkeddata.es/def/adapters#GridVoltage',
  'https://auroral.iot.linkeddata.es/def/adapters#HeartRate',
  'https://auroral.iot.linkeddata.es/def/adapters#HighClouds',
  'https://auroral.iot.linkeddata.es/def/adapters#HourlyPersonCounter',
  'https://auroral.iot.linkeddata.es/def/adapters#Illuminance',
  'https://auroral.iot.linkeddata.es/def/adapters#IndoorAmbientTemperature',
  'https://auroral.iot.linkeddata.es/def/adapters#InstantaneousActivePower',
  'https://auroral.iot.linkeddata.es/def/adapters#InstantaneousApparentPower',
  'https://auroral.iot.linkeddata.es/def/adapters#InstantaneousCapacitiveInductivePower',
  'https://auroral.iot.linkeddata.es/def/adapters#InstantaneousReactiveInductivePower',
  'https://auroral.iot.linkeddata.es/def/adapters#InstantaneousReactivePower',
  'https://auroral.iot.linkeddata.es/def/adapters#LightColor',
  'https://auroral.iot.linkeddata.es/def/adapters#LowClouds',
  'https://auroral.iot.linkeddata.es/def/adapters#MaximumPrecipitation',
  'https://auroral.iot.linkeddata.es/def/adapters#MaximumTemperature',
  'https://auroral.iot.linkeddata.es/def/adapters#Medium_Clouds',
  'https://auroral.iot.linkeddata.es/def/adapters#MinimumPrecipitation',
  'https://auroral.iot.linkeddata.es/def/adapters#MinimumTemperature',
  'https://auroral.iot.linkeddata.es/def/adapters#Motion',
  'https://auroral.iot.linkeddata.es/def/adapters#MuscleMass',
  'https://auroral.iot.linkeddata.es/def/adapters#NH3Concentration',
  'https://auroral.iot.linkeddata.es/def/adapters#NO2Concentration',
  'https://auroral.iot.linkeddata.es/def/adapters#NOConcentration',
  'https://auroral.iot.linkeddata.es/def/adapters#NoiseLevel',
  'https://auroral.iot.linkeddata.es/def/adapters#O3Concentration',
  'https://auroral.iot.linkeddata.es/def/adapters#Off',
  'https://auroral.iot.linkeddata.es/def/adapters#On',
  'https://auroral.iot.linkeddata.es/def/adapters#OperationalStatus',
  'https://auroral.iot.linkeddata.es/def/adapters#OutdoorAmbientTemperature',
  'https://auroral.iot.linkeddata.es/def/adapters#PM10Concentration',
  'https://auroral.iot.linkeddata.es/def/adapters#PM1_0Concentration',
  'https://auroral.iot.linkeddata.es/def/adapters#PM2_5Concentration',
  'https://auroral.iot.linkeddata.es/def/adapters#Periodic',
  'https://auroral.iot.linkeddata.es/def/adapters#PowerFactor',
  'https://auroral.iot.linkeddata.es/def/adapters#PowerOn',
  'https://auroral.iot.linkeddata.es/def/adapters#ProbabilityPrecipitation',
  'https://auroral.iot.linkeddata.es/def/adapters#Protein',
  'https://auroral.iot.linkeddata.es/def/adapters#Pulse',
  'https://auroral.iot.linkeddata.es/def/adapters#Rainfall',
  'https://auroral.iot.linkeddata.es/def/adapters#ReactiveCpacitiveEnergy',
  'https://auroral.iot.linkeddata.es/def/adapters#ReactiveInductiveEnergy',
  'https://auroral.iot.linkeddata.es/def/adapters#RelativeHumidity',
  'https://auroral.iot.linkeddata.es/def/adapters#ReturnedEnergy',
  'https://auroral.iot.linkeddata.es/def/adapters#SO2Concentration',
  'https://auroral.iot.linkeddata.es/def/adapters#SelectableStatus',
  'https://auroral.iot.linkeddata.es/def/adapters#Sensor',
  'https://auroral.iot.linkeddata.es/def/adapters#ShortwaveRadiationInstant',
  'https://auroral.iot.linkeddata.es/def/adapters#Sleep',
  'https://auroral.iot.linkeddata.es/def/adapters#Snowfall',
  'https://auroral.iot.linkeddata.es/def/adapters#Steps',
  'https://auroral.iot.linkeddata.es/def/adapters#SugarLevel',
  'https://auroral.iot.linkeddata.es/def/adapters#SystolicBloodPressure',
  'https://auroral.iot.linkeddata.es/def/adapters#TerrestrialRadiation',
  'https://auroral.iot.linkeddata.es/def/adapters#TerrestrialRadiationInstant',
  'https://auroral.iot.linkeddata.es/def/adapters#Thunder',
  'https://auroral.iot.linkeddata.es/def/adapters#TotalBodyWaterPercentage',
  'https://auroral.iot.linkeddata.es/def/adapters#TotalEnergy',
  'https://auroral.iot.linkeddata.es/def/adapters#UVIndex',
  'https://auroral.iot.linkeddata.es/def/adapters#Unavailable',
  'https://auroral.iot.linkeddata.es/def/adapters#Vibration',
  'https://auroral.iot.linkeddata.es/def/adapters#VisceralFatRating',
  'https://auroral.iot.linkeddata.es/def/adapters#WeatherCondition',
  'https://auroral.iot.linkeddata.es/def/adapters#Weight',
  'https://auroral.iot.linkeddata.es/def/adapters#WindGust',
  'https://auroral.iot.linkeddata.es/def/adapters#XAxisAcceleration',
  'https://auroral.iot.linkeddata.es/def/adapters#YAxisAcceleration',
  'https://auroral.iot.linkeddata.es/def/adapters#ZAxisAcceleration',
  'https://auroral.iot.linkeddata.es/def/adapters#windSpeed',
]

export const omOntologyTypes = [
  'http://www.ontology-of-units-of-measure.org/resource/om-2/Length',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/Mass',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/Time',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/Temperature',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/Area',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/Volume',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/Speed',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/Frequency',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/Energy',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/Power',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/Force',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/ElectricCurrent',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/ElectricPotential',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/MassFraction',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/Density',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/metre',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/kilometre',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/centimetre',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/millimetre',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/inch-International',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/foot-International',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/mile-Statute',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/yard-International',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/kilogram',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/gram',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/milligram',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/poundAvoirdupois',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/ounceAvoirdupois',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/second-Time',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/millisecond-Time',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/minute-Time',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/hour',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/day',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/week',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/month',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/year',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/kelvin',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/degreeCelsius',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/degreeFahrenheit',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/squareMetre',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/squareCentimetre',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/squareKilometre',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/are',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/hectare',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/acre-International',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/acre-USSurvey',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/cubicMetre',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/cubicCentimetre',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/litre',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/decilitre',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/centilitre',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/millilitre',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/pint-Imperial',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/liquidPint-US',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/gallon-Imperial',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/gallon-US',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/metrePerSecond-Time',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/kilometrePerHour',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/mile-StatutePerHour',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/hertz',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/kilohertz',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/megahertz',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/joule',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/kilojoule',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/kilocalorie-Mean',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/kilowattHour',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/watt',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/milliwatt',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/kilowatt',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/megawatt',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/newton',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/kilonewton',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/pound-Force',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/ampere',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/milliampere',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/volt',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/millivolt',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/gramPerKilogram',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/percent',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/gramPerLitre',
  'http://www.ontology-of-units-of-measure.org/resource/om-2/milligramPerLitre',
]
